---
- hosts: my_servers
  become: true
  become_method: runas
  become_user: Administrator
  
  tasks:
    - name: Change the hostname
      ansible.windows.win_hostname:
        name: "ABISS1"
      register: res
  
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
