---
- hosts: my_servers
  become: true
  become_method: runas
  become_user: Administrator
  
  tasks:
    - name: Create directory
      win_file:
        path: C:\Temp\folder
        state: directory
