---
- hosts: my_servers
  become: true
  become_method: runas
  become_user: Administrator
  
  tasks:
    - name: Creates directory for WSUS DB
      ansible.builtin.file:
        path: C:\WSUS_DB
        state: directory
        
    - name: Install Windows Server Update Services (WSUS)
      win_feature:
        name:
          - UpdateServices
          - UpdateServices-WidDB
        include_management_tools: yes
        state: present
      register: res
  
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
