---
- hosts: my_servers
  become: true
  become_method: runas
  become_user: Administrator
  
  tasks:
    - name: Install Windows Server Update Services (WSUS)
      win_feature: >
        name=UpdateServices
        include_management_tools=yes
        include_sub_features=yes
        state=present
      register: result
  
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
